### ISSUE TITLE
online demo?

### ISSUE THREAD

**Issue by trusktr** [dinopetrone/rich-todo#1]
?

**Comment by trusktr** [comment]
Nevermind, it's here: http://dinopetrone.github.io/rich-todo/src/

Would be nice if it showed off more of famo.us' features like physics, 3D, etc.

Please, if you could update it so the add or trash animations are some type of 3D, that'd be great!!

**Comment by dinopetrone** [comment]
sorry @trusktr  just saw this.  You can view an online demo here:

http://www.blitzagency.com/

We actually built rich with the intent of building this site.

**Comment by trusktr** [comment]
That's awesome. I saw blitz. It's one of the nicest Famo.us production examples in
the wild! I also really like the idea of cassowary based layout being
rendered with Famo.us. Seems like a really good idea!

**Comment by dinopetrone** [comment]
why thank you good sir :)  glad you liked it
